version: "3"
services:
  api:
    container_name: api_haumea
    depends_on:
      - db
    restart: always
    env_file:
      - .env
    build: .
    ports:
      - '${PORT}:${PORT}'
    environment:
      - DB_URL=DB_URI
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    links: 
      - db  

  db:
    image: mongo
    container_name: mongo_haumea
    restart: always
    env_file:
      - .env
    volumes:
      - mongodata:/data/db
    ports:
      - '${DB_PORT}:${DB_PORT}'

volumes:
  mongodata: